#! /bin/bash
# Forked from plan-debug, commented out all echo statements
# so the output is cleaner. This is called by scripts under ../xuy-scripts for running experients.
set -e

BASEDIR="$(dirname "$0")"

function die {
    echo "$@" 1>&2
    exit 1
}

function usage {
    die "usage: $(basename "$0") [DOMAIN_FILE] PROBLEM_FILE SEARCH_OPTION ..."
}

# Paths to planner components
TRANSLATE="$BASEDIR/translate/translate.py"
PREPROCESS="$BASEDIR/preprocess/preprocess"
SEARCH="$BASEDIR/search/downward-2-debug"

# Need to explicitly ask for GNU time (from MacPorts) on Mac OS X.
if [[ "$(uname)" == "Darwin" ]]; then
    TIME="gtime"
    if ! which $TIME >/dev/null; then
        die "$TIME must be installed on Mac OSX (from MacPorts, perhaps) for this to work"
    fi
else
    TIME="command time"
fi

TIME="$TIME --output=elapsed.time --format=%S\n%U\n"

if [[ "$#" < 2 ]]; then
    usage
fi

#echo "1. Running translator"
if [[ -e "$2" ]]; then
    #echo "Second argument is a file name: use two translator arguments."
    $TIME "$TRANSLATE" "$1" "$2" > /dev/null
    shift 2
else
    #echo "Second argument is not a file name: auto-detect domain file."
    $TIME "$TRANSLATE" "$1" > /dev/null
    shift
fi
#echo

#echo "2. Running preprocessor"
$TIME --append "$PREPROCESS" < output.sas > /dev/null
#echo

#echo "3. Running search"
"$SEARCH" < output "$@"
#echo
